config/routes.rb
Kgcash::Application.routes.draw do

root :to => 'welcome#index', :constraints => UserRequiredConstraint.new
root :to => 'static_pages#home', :constraints => NoUserRequiredConstraint.new, as: nil

resources :user_sessions

resources :users

resources :transactions, constraints: { id: /\d+/ } do
  get 'new_attachment'
  patch 'update_attachment'
  delete 'delete_attachment'
  collection do
    get 'uncategorized'
    post 'autocategorize'
  end
end

get 'transactions/search', to: 'transactions#search'

resources :documents

resources :transaction_imports

resources :expenses do
  collection do
    post 'split_commit'
  end
  collection do
    get 'split'
  end
end

resources :incomes

resources :payments

resources :asset_transfers

resources :reports do
  collection do
    get 'income', to: 'reports#income'
    get 'cashflow', to: 'reports#cashflow'
    get 'alltime', to: 'reports#alltime'
    get 'alltime_expenses', to: 'reports#alltime_expenses'
    get 'alltime_revenue', to: 'reports#alltime_revenue'
  end
end

resources :accounts do
  collection do
    get 'spending'
  end
end

resources :categories

resources :notes

match 'login' => 'user_sessions#new', :as => :login, via: [:get, :post]
match 'logout' => 'user_sessions#destroy', :as => :logout, via: [:get, :post]

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :related_transaction, class_name: 'Transaction', optional: true
  belongs_to :user

  validates :note_text, presence: true
  validates :amount, numericality: true
  validates :user, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = current_user.notes
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      respond_to do |format|
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json {render json: @note}
    end
  end

  def update
    if @note.update(note_params)
      respond_to do |format|
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render json: @note }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_note
    @user = current_user
    @note = current_user.notes.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:note_text, :amount, :transaction_id)
  end
end

app/views/notes/_form.html.erb
<%= form_with(model: @note, local: true) do |form| %>
  <div class="row px-4">
    <table class="table">
      <tbody>
        <tr>
          <td class="bg-light"><strong>Text</strong></td>
          <td><%= form.text_area :note_text, class: 'form-control' %></td>
        </tr>
        <tr>
          <td class="bg-light"><strong>Amount</strong></td>
          <td><%= form.number_field :amount, class: 'form-control' %></td>
        </tr>
      </tbody>
    </table>

    <table class="table table-borderless">
      <thead>
        <tr>
          <td>
            <%= link_to 'Save', '#', class: 'btn btn-primary', id: 'submit-form' %>
            <% if !@note.id.nil? %>
              <%= link_to 'Delete', note_path(@note), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
            <%= link_to "Back to notes", notes_path, class: 'btn btn-secondary' %>
          </td>
        </tr>
      </thead>
    </table>
  </div>
<% end %>

<script>
  document.getElementById('submit-form').addEventListener('click', function(e) {
    e.preventDefault();
    document.querySelector('form').submit();
  });
</script>

app/views/notes/edit.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-6">
			<h2 class="text-center">Edit Note</h2>

			<%= render 'form' %>

		</div>
	</div>
</div>

app/views/notes/index.html.erb
<div class="col-md-8 mx-auto">

	<h3>My Notes</h3>

	<table class="table table-striped">
		<thead>
			<tr>
				<th class="text-center">Date</th>
				<th>Note Text</th>
				<th class="text-center">Amount</th>
				<th class="text-center">Transaction</th>
				<th class="text-center">Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @notes.each do |note| %>
				<tr>
					<td class="text-center"><%= note.updated_at.strftime("%b %d, %Y") %></td>
					<td><%= note.note_text %></td>
					<td class="text-center"><%= number_to_currency(note.amount) %></td>
					<td class="text-center"><%= note.related_transaction&.name %></td>
					<td class="text-center">
						<div class="dropdown">
							<a class="btn btn-sm" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								...
							</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
								<%= link_to 'Show', note_path(note), class: 'dropdown-item' %>
								<%= link_to 'Edit', edit_note_path(note), class: 'dropdown-item' %>
								<%= link_to 'Delete', note_path(note), method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %>
							</div>
						</div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<%= link_to 'New Note', new_note_path, class: 'btn btn-success' %>
</div>

<br />

app/views/notes/new.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-6">
			<h2 class="text-center">New Note</h2>

			<%= render 'form' %>

		</div>
	</div>
</div>

app/views/notes/show.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-6">
			<h2>Note Details</h2>
			<table class="table">
				<tbody>
					<tr>
						<td class="bg-light" style="width: 30%;"><strong>Date</strong></td>
						<td><%= @note.updated_at.strftime("%b %d, %Y") %></td>
					</tr>
					<tr>
						<td class="bg-light" style="width: 30%;"><strong>Note Text</strong></td>
						<td><%= @note.note_text %></td>
					</tr>
					<tr>
						<td class="bg-light" style="width: 30%;"><strong>Amount</strong></td>
						<td><%= @note.amount %></td>
					</tr>
					<tr>
						<td class="bg-light" style="width: 30%;"><strong>Transaction</strong></td>
						<td><%= @note.related_transaction&.name %></td>
					</tr>
				</tbody>
			</table>

			<%= link_to 'Edit', edit_note_path(@note), class: 'btn btn-primary' %>
			<%= link_to 'Back to Notes', notes_path, class: 'btn btn-secondary' %>
		</div>
	</div>
</div>