config/routes.rb
Kgcash::Application.routes.draw do

root :to => 'welcome#index', :constraints => UserRequiredConstraint.new
root :to => 'static_pages#home', :constraints => NoUserRequiredConstraint.new, as: nil

resources :user_sessions

resources :users

resources :transactions, constraints: { id: /\d+/ } do
  get 'new_attachment'
  patch 'update_attachment'
  delete 'delete_attachment'
  collection do
    get 'uncategorized'
    post 'autocategorize'
  end
end

get 'transactions/search', to: 'transactions#search'

resources :documents

resources :transaction_imports

resources :expenses do
  collection do
    post 'split_commit'
  end
  collection do
    get 'split'
  end
end

resources :incomes

resources :payments

resources :asset_transfers

resources :reports do
  collection do
    get 'income', to: 'reports#income'
    get 'cashflow', to: 'reports#cashflow'
    get 'alltime', to: 'reports#alltime'
    get 'alltime_expenses', to: 'reports#alltime_expenses'
    get 'alltime_revenue', to: 'reports#alltime_revenue'
  end
end

resources :accounts do
  collection do
    get 'spending'
  end
end

resources :categories

resources :notes

match 'login' => 'user_sessions#new', :as => :login, via: [:get, :post]
match 'logout' => 'user_sessions#destroy', :as => :logout, via: [:get, :post]

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	include TransactionControllerConcern

	def show

		@user = current_user
		if @user == nil
			@user = User.last
		end
		@transaction = @user.transactions.find(params[:id])

		sJoinsAccounts = "LEFT JOIN accounts as accts_cr ON accts_cr.id = transactions.acct_id_cr"

		@pagy, @transactions = pagy(@user.transactions
			.joins(sJoinsAccounts)
			.select("transactions.id, tx_date, credit, credit as 'amount', debit, tx_type, details, notes, acct_id_cr, acct_id_dr, parent_id, "\
			"IF(accts_cr.account_type = 'Expense', 'credit', 'debit') as txType, "\
			"(SELECT COUNT(*) from active_storage_attachments A WHERE A.record_id = transactions.id AND A.record_type = 'Transaction' and A.name = 'attachment' ) as attachments"
			)
			.where("(acct_id_dr in (select id from accounts where account_type = 'Asset' or account_type = 'Liability') "\
				"AND acct_id_cr in (select id from accounts where account_type = 'Expense')) "\
					"OR "\
				"(acct_id_cr in (select id from accounts where account_type = 'Asset' or account_type = 'Liability') "\
				"AND acct_id_dr in (select id from accounts where account_type = 'Expense'))")
			.where(parent_id: params[:id])
			.order(sort_column + ' ' + sort_direction))

		respond_to do |format|
			format.html #show.html.erb
			format.json {render json: @transaction}
		end
	end

	def edit
		@user = current_user
		@transaction = @user.transactions.find(params[:id])
		@accounts = @user.account_selector
	end

	def create
		@user = current_user

		@transaction = @user.transactions.create(transaction_params)

		respond_to do |format|
			if @transaction.save
				format.html { redirect_to(transactions_path, :notice => 'Transaction was successfully created for user.') }
				format.json { render json: @transaction, status: :created, location: @transaction }
			else
				format.html { render action: "new" }
				format.json { render json: @transaction.errors, status: :unprocessable_entity }
			end
		end
	end

	def update

		user = current_user
		@transaction = user.transactions.find(params[:id])

		respond_to do |format|
			if @transaction.update(transaction_params)
				format.html {  redirect_to transactions_path, notice: 'Transaction was successfully updated.' }
				format.json { respond_with_bip(@transaction) }
				format.js {
					redirect_to transactions_path
					# render :nothing => true, :status => 200, :content_type => 'text/html' 
				}
			else
				format.html { render action: "edit" }
				format.json { render json: @transaction.errors, status: :unprocessable_entity }
			end
		end
	end


	def new
		@user = current_user
		@dateTx = DateTime.now
		@transaction = Transaction.new
		@transaction.tx_date = @dateTx
		@transaction.posting_date = @dateTx
		@accounts = @user.account_selector

		@user.transactions << @transaction

		respond_to do |format|
			format.html # new.html.erb
			format.json {render json: @transaction}
		end
	end

	def destroy
		@user = current_user
		@transaction = @user.transactions.find(params[:id])
		@transaction.destroy

		respond_to do |format|
			format.html { redirect_back(fallback_location: root_path) }
			format.js   { render :nothing => true }
			format.json { head :ok }
		end
	end

	def index
		@user = current_user

		@year = params.has_key?(:year) ? params[:year].to_i : Date.today.year
		account = params.has_key?(:account) ? params[:account].to_i : nil

		@pagy, @transactions = pagy(@user.transactions
			.select("id, tx_date, credit, debit, tx_type, details, notes, acct_id_cr, acct_id_dr, parent_id")
			.in_year(@year)
			.order(sort_column + ' ' + sort_direction))

		respond_to do |format|
			format.html #index.html.erb
			format.csv {}
		end
	end

	def new_attachment
		transaction_id = params.has_key?(:transaction_id) ? params[:transaction_id] : nil
		@transaction = Transaction.find(transaction_id)
		respond_to do |format|
			format.html
			format.js
		end
	end

	def update_attachment
		transaction_id = params.has_key?(:transaction_id) ? params[:transaction_id] : nil
		@transaction = Transaction.find(transaction_id) 
		@transaction.attachment.attach(params[:transaction][:attachment])
		respond_to do |format|
			format.html { redirect_back fallback_location: transactions_url }
			format.json { head :no_content }
		end
	end

	def delete_attachment
		transaction_id = params.has_key?(:transaction_id) ? params[:transaction_id] : nil
		transaction = Transaction.find(transaction_id)
		if transaction.attachment.attached?
			transaction.attachment.purge
		end

		respond_to do |format|
			format.html { redirect_back fallback_location: transactions_url }
			format.json { head :no_content }
		end
	end

	def uncategorized
		@user = current_user
		@tx_type = (params.has_key?(:tx_type) && params[:tx_type] == 'credit') ? 'credit' : 'debit'

		nullField = @tx_type == 'credit' ? 'acct_id_cr' : 'acct_id_dr'
		amountField = @tx_type == 'credit' ? "debit as 'amount'" : "credit as 'amount'"
		txTypeField = @tx_type == 'credit' ? "'credit' as 'txType'" : "'debit' as 'txType'"

		@year = params.has_key?(:year) ? params[:year].to_i : Date.today.year
		@month = params.has_key?(:month) ? params[:month].to_i : nil

		@pagy, @transactions = pagy(@user.transactions
			.select("id, tx_date, credit, debit, " + amountField + ", tx_type, details, notes, "\
				"acct_id_cr, acct_id_dr, acct_id_dr_proposed, acct_id_cr_proposed, parent_id, " + txTypeField + ", "\
				"(SELECT COUNT(*) from active_storage_attachments A WHERE A.record_id = transactions.id AND A.record_type = 'Transaction' and A.name = 'attachment' ) as attachments"
			)
			.where("(" + nullField + " IS NULL)")
			.in_month_year(@month, @year)
			.order(sort_column + ' ' + sort_direction))

		@display_type = @tx_type == 'credit' ? 'income' : 'expense'
		@title = "Uncategorized " + @display_type[0].capitalize + @display_type[1..-1] + " Transactions"

		respond_to do |format|
			format.html #index.html.erb
		end
	end

	def search
		@user = current_user
		query = params[:q]

		@pagy, @transactions = pagy(@user.transactions
						 .where("MATCH(details, notes) AGAINST(?)", query)
						 .order(sort_column + ' ' + sort_direction))

		respond_to do |format|
			format.html { render :index }
		end
	end

	def autocategorize
		@user = current_user

		tx_ids = params.has_key?(:transactions) ? JSON.parse(params[:transactions]) : nil

		@user.transactions.where(id: tx_ids).each do |tx|

			# Find a good searchable string
			details = tx.details.nil? ? "" : tx.details.gsub(/Vancouver BC/i, "")
			longest_substring = details.scan(/[a-zA-Z\s\.\*']+/).max_by(&:length).strip

			# Find similar transactions using the search string
			tx_similar = @user.transactions
				.where("MATCH(details, notes) AGAINST(?)", longest_substring)
				.where("acct_id_cr = ?", tx.acct_id_cr)
				.where("YEAR(tx_date) > ?", Date.today.year - 2)

			# Count the instances of each account category
			hash_similar = {}
			tx_count = 0
			tx_similar.each do |tx_sim|
				if !tx_sim.acct_id_dr.nil?
					hash_similar.has_key?(tx_sim.acct_id_dr) ? hash_similar[tx_sim.acct_id_dr] += 1 : hash_similar[tx_sim.acct_id_dr] = 1
					tx_count += 1
				end
			end

			next if hash_similar.empty?

			hash_similar = hash_similar.sort_by { |k, v| v }.reverse.to_h
			hash_similar.each do |k, v|
				hash_similar[k] = v / tx_count.to_f
			end

			best_guess = {}
			hash_similar.each do |k, v|
				if v > 0.3
					best_guess[k] = v
				end
			end

			next if best_guess.empty?

			tx.update(acct_id_dr_proposed: best_guess, acct_id_dr_proposed_source: "search")

		end

		page = params.has_key?(:page) ? params[:page] : 1
		redirect_to uncategorized_transactions_path, page: page, notice: 'Transactions have been autocategorized.'
	end

	private

	def transaction_params
		params.require(:transaction).permit(:name, :description, :account_type, :year, :id, :credit,
			:acct_id_dr, :acct_id_dr_proposed, :debit, :tx_type, :details, :notes, 
			:acct_id_cr, :acct_id_cr_proposed, :tx_date, :posting_date, :q)
	end

end

app/views/transactions/_asset_transfers_list.html.erb
<table class="table table-striped table-condensed">
	<tr>
		<th width="120px"><%= sortable "tx_date", "Date" %></th>
		<th>FROM</th>
		<th>TO</th>
		<th><%= sortable "details" %></th>
		<th><%= sortable "notes" %></th>
		<th class="text-center" width="75px"><%= sortable "credit", "Amount" %></th>
		<th width="48" class="text-center">Details</th>
	</tr>

<% @transactions.each_with_index do |transaction, idx| %>
	<% txAmountClass = transaction.txType %>

	<tr>
		<td class="tx"><%= best_in_place transaction, :tx_date, :as => :date, :display_as => :format_date %></td>
		<td class="tx">
			<%= form_for transaction, :remote => true do |f| %>
				<%= f.select 'acct_id_cr', options_from_collection_for_select(@user.sortedAccounts,'id','name', transaction['acct_id_cr']), { :include_blank => "select type"}, :class => 'transaction_update select', tabindex: ((idx+1)*2)+1 %>
			<% end %>
		</td>
		<td class="tx"><%= form_for transaction, :remote => true do |f| %>
			<%= f.select 'acct_id_dr', options_from_collection_for_select(@user.sortedAccounts,'id','name', transaction['acct_id_dr']), {}, :class => 'transaction_update select', tabindex: "-1" %>
			<% end %>
		</td>
		<td class="tx"><%= best_in_place transaction, :details, :as => :textarea %></td>
		<td class="tx"><%= best_in_place transaction, :notes, :class => 'expense_note', tabindex: (idx+1)*2 %></td>
		<td class="text-center tx <%= txAmountClass %>"><%= number_to_currency(transaction.amount) %></td>
		<td class="text-center tx">
			<div class="d-flex justify-content-between">
				<div class="dropdown">
					<a class="btn btn-sm" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						...
					</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
						<a class="dropdown-item" href="<%= edit_transaction_path(:id => transaction.id)%>">Edit</a>
						<a class="dropdown-item" href="<%= transaction_path(:id => transaction.id)%>">View</a>
						<% if !transaction.attachment.attached? %>
							<%= link_to( "Add Attachment", transaction_new_attachment_path(:transaction_id => transaction.id), {:remote => true, 'data-toggle' => 'modal', 'data-backdrop'=>'static','data-target' => '#modal-window', class: "dropdown-item"})  %>
						<% end %>
						<%= link_to( "Delete", transaction, method: :delete, data: { confirm: 'Delete Transaction?' }, class: "dropdown-item") %>
					</div>
				</div>
				<div class="dropdown d-flex justify-content-between">
					<div class="float-start">
						<% if transaction.attachment.attached? %>
							<a href="#" id="attachmentDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<%= image_tag("attachment.png", height: '16', width: '16') %>
							</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="attachmentDropdownMenuButton">
								<%= link_to( "Show Attachment", url_for(transaction.attachment), class: "dropdown-item" ) %>
								<%= link_to( 'Delete Attachment', transaction_delete_attachment_url(transaction),
									method: :delete,
									class: "dropdown-item",
									data: { confirm: 'Are you sure?' }) %>
							</div>
						<% end %>
					</div>
					<div>
						<% if !transaction.parent_id.nil? %>
							<a href="#" id="connectedDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<%= image_tag("connected.png", height: '16', width: '16') %>
							</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="connectedDropdownMenuButton">
								<%= link_to( "Show Related", transaction_path(:id => transaction.parent_id), class: "dropdown-item" ) %>
							</div>
						<% else %>
							<%= image_tag("empty.png", height: '16', width: '16') %>
						<% end %>

					</div>
				</div>
			</div>
		</td>
	</tr>
<% end %>
</table>

<div id="modal-window" class="modal hide" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/transactions/_form.html.erb
<%= form_with(model: @transaction, local: true) do |form| %>
  <div class="row px-4">
    <div class="col-md-3">

      <table class="table">
        <tbody>
          <tr>
            <td class="bg-light"><strong>Transaction Date</strong></td>
            <td><%= form.text_field :tx_date, class: 'form-control' %></td>
          </tr>
          <tr>
            <td class="bg-light"><strong>Posting Date</strong></td>
            <td><%= form.text_field :posting_date, class: 'form-control' %></td>
          </tr>
          <tr>
            <td class="bg-light"><strong>Account ID (Credit)</strong></td>
            <td><%= form.select :acct_id_cr, @accounts, {}, class: 'form-control' %></td>
          </tr>
          <tr>
            <td class="bg-light"><strong>Credit Amount</strong></td>
            <td><%= form.text_field :credit, class: 'form-control' %></td>
          </tr>
          <tr>
            <td class="bg-light"><strong>Account ID (Debit)</strong></td>
            <td><%= form.select :acct_id_dr, @accounts, {}, class: 'form-control' %></td>
          </tr>
          <tr>
            <td class="bg-light"><strong>Debit Amount</strong></td>
            <td><%= form.text_field :debit, class: 'form-control' %></td>
          </tr>

          <tr>
            <td class="bg-light"><strong>Details</strong></td>
            <td><%= form.text_field :details, class: 'form-control' %></td>
          </tr>
          <tr>
            <td class="bg-light"><strong>Notes</strong></td>
            <td><%= form.text_field :notes, class: 'form-control' %></td>
          </tr>
        </tbody>
      </table>

      <table class="table table-borderless">
        <thead>
          <tr>
            <td>
              <%= link_to 'Save', '#', class: 'btn btn-primary', id: 'submit-form' %>
              <% if !@transaction.id.nil? %>
                <%= link_to 'Delete', transaction_path(@transaction), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              <% end %>
              <%= link_to "Back to transactions", transactions_path, class: 'btn btn-secondary' %>
            </td>
          </tr>
        </thead>
      </table>
    </div>
  </div>
<% end %>

<script>
  document.getElementById('submit-form').addEventListener('click', function(e) {
    e.preventDefault();
    document.querySelector('form').submit();
  });
</script>

app/views/transactions/_transaction_list.html.erb
<% transactionType = '' %>
<table id="transactions" class="table table-striped table-condensed">
  <tr>
	<th width="140px"><%= sortable "tx_date", "Date" %></th>
	<th>Debit Account</th>
	<th class="text-center"><%= sortable "debit", "Amount" %></th>
	<th>Credit Account</th>
	<th class="text-center"><%= sortable "credit", "Amount" %></th>
	<th><%= sortable "details" %></th>
	<th><%= sortable "notes" %></th>
	<th class="text-center">Details</th>
  </tr>

<% (defined?(transactions) ? transactions : @transactions).each_with_index do |transaction, idx| %>
<% txCredit = (transaction.credit.nil? ? 0 : transaction.credit) %>
<% txDebit = (transaction.debit.nil? ? 0 : transaction.debit) %>
  <tr>
	<td class="align-middle"><%= best_in_place transaction, :tx_date, :as => :date, :display_as => :format_date %></td>
	<td class="align-middle"><%= form_for transaction, :remote => true do |f| %>
		<%= f.select :acct_id_dr, options_from_collection_for_select(@user.sortedAccounts,'id','name', transaction.acct_id_dr), { :include_blank => "select type"}, :class => 'transaction_update mt-0', tabindex: ((idx+1)*2)+1 %>
	<% end %>
	</td>
	<td class="debit text-center align-middle"><%= number_to_currency(txDebit) %></td>
	<td class="align-middle"><%= form_for transaction, :remote => true do |f| %>
			<%= f.select :acct_id_cr, options_from_collection_for_select(@user.sortedAccounts,'id','name', transaction.acct_id_cr), {}, :class => 'transaction_update mt-0', tabindex: "-1" %>
		<% end %>
	</td>	
	<td class="credit text-center align-middle"><%= number_to_currency(txCredit) %></td>
	<td class="align-middle"><%= best_in_place transaction, :details, :as => :textarea %></td>
	<td class="align-middle"><%= best_in_place transaction, :notes, :class => 'expense_note', tabindex: (idx+1)*2 %></td>
	<td class="text-center tx align-middle">
		<div class="d-flex justify-content-between">
			<div class="dropdown">
				<a class="btn btn-sm" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					...
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
					<a class="dropdown-item" href="<%= edit_transaction_path(:id => transaction.id)%>">Edit</a>
					<a class="dropdown-item" href="<%= transaction_path(:id => transaction.id)%>">View</a>
					<% if transactionType == 'expense'%>
						<a class="dropdown-item" href="<%= split_expenses_path(:id => transaction.id)%>">Split</a>
					<% end %>
					<% if transaction[:attachments] == 0 %>
						<%= link_to( "Add Attachment", transaction_new_attachment_path(:transaction_id => transaction.id), {:remote => true, 'data-toggle' => 'modal', 'data-backdrop'=>'static','data-target' => '#modal-window', class: "dropdown-item"})  %>
					<% end %>
					<%= link_to( "Delete", transaction, method: :delete, data: { confirm: 'Delete Transaction?' }, class: "dropdown-item") %>
				</div>
			</div>
			<div class="dropdown d-flex justify-content-between">
				<div class="float-start">
					<% if !transaction[:attachments].nil? && transaction[:attachments] > 0 %>
						<a href="#" id="attachmentDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<%= image_tag("attachment.png", height: '16', width: '16') %>
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="attachmentDropdownMenuButton">
							<%= link_to( "Show Attachment", url_for(transaction.attachment), class: "dropdown-item" ) %>
							<%= link_to( 'Delete Attachment', transaction_delete_attachment_url(transaction),
								method: :delete,
								class: "dropdown-item",
								data: { confirm: 'Are you sure?' }) %>
						</div>
					<% end %>
				</div>
				<div>
					<% if !transaction.parent_id.nil? %>
						<a href="#" id="connectedDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<%= image_tag("connected.png", height: '16', width: '16') %>
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="connectedDropdownMenuButton">
							<%= link_to( "Show Related", transaction_path(:id => transaction.parent_id), class: "dropdown-item" ) %>
						</div>
					<% else %>
						<%= image_tag("empty.png", height: '16', width: '16') %>
					<% end %>

				</div>
			</div>
		</div>
	</td>
  </tr>
<% end %>
</table>

app/views/transactions/_typed_transaction_list.html.erb
<% transactionType = (local_assigns[:txType]) ? txType : 'expense' %>
<% categoryAccountType = transactionType == 'expense' ? 'acct_id_dr' : 'acct_id_cr' %>
<% txAccountType = transactionType == 'expense' ? 'acct_id_cr' : 'acct_id_dr' %>
<% txAmountToUpdate = transactionType == 'expense' ? 'debit' : 'credit' %>
<% txAmountSortColumn = (local_assigns[:txAmountSort]) ? txAmountSort : 'credit' %>

<table id="transactions" class="table table-striped table-condensed">
	<tr>
		<th width="120px"><%= sortable "tx_date", "Date" %></th>
		<th><%= sortable "account_id", "Account" %></th>
		<th><%= sortable "details" %></th>
		<th><%= sortable "notes" %></th>
		<th class="text-center" width="75px"><%= sortable txAmountSortColumn, "Amount" %></th>
		<th>Category</th>
		<th>Suggested</th>
		<th width="48" class="text-center">Details</th>
	</tr>

<% tabIndex = 1%>

<% @transactions.each_with_index do |transaction, idx| %>
	<% txAmountClass = transaction.respond_to?(:txType) ? transaction.txType :  'credit'%>
	<% has_acct_dr_proposed = false%>
	<% tabIndex = tabIndex+4%>
	<% tx_dr_id = transaction.acct_id_dr %>
	<% if transaction.acct_id_dr.nil? && !transaction.acct_id_dr_proposed.nil? %>
		<% has_acct_dr_proposed = true %>
		<% tx_dr_proposed = Hash[transaction.acct_id_dr_proposed.tr("{} ", "").split(',').map { |pair| pair.split('=>') }] %>
	<% end %>
	<tr>
		<td class="tx align-middle"><%= best_in_place transaction, :tx_date, :as => :date, :display_as => :format_date %></td>
		<td class="tx align-middle"><%= form_for transaction, :remote => true do |f| %>
				<%= f.select txAccountType, options_from_collection_for_select(@user.sortedAccounts,'id','name', transaction[txAccountType]), {}, :class => 'transaction_update select', tabindex: "-1" %>
			<% end %>
		</td>
		<td class="tx align-middle"><%= best_in_place transaction, :details, :as => :textarea %></td>
		<td class="tx align-middle"><%= best_in_place transaction, :notes, :class => 'expense_note', tabindex: tabIndex %></td>
		<td class="text-center tx align-middle <%= txAmountClass %>"><%= number_to_currency(transaction.amount) %></td>
		<td class="tx align-middle" style="width: 1px; white-space: nowrap;"><%= form_for transaction, :remote => true do |f| %>
			<%= f.hidden_field txAmountToUpdate, value: [transaction.debit.to_f, transaction.credit.to_f].max() %>
			<%= f.hidden_field categoryAccountType + "_proposed", value: nil %>
			<%= f.select categoryAccountType, options_from_collection_for_select(@user.sortedAccounts,'id','name', transaction[categoryAccountType]), { :include_blank => "select type"},
				:id => categoryAccountType + '-' + transaction.id.to_s, :class => 'transaction_update select', tabindex: tabIndex+1 %>
		<% end %>
		</td>
		<td class="tx align-middle align-left">
			<% if has_acct_dr_proposed %>
				<% tx_dr_proposed.each_with_index do |(k,v),idx|%>
					<% certainty = v.to_f > 0.9 ? "success" : "info"%>
					<%= form_for transaction, :remote => true, :class => 'float:right' do |f| %>
						<span id=<%= categoryAccountType + "-" + transaction.id.to_s + "-" + k.to_s %>
							class="badge <%= "badge-" + certainty %> transaction_pill"
							tabindex=<%=tabIndex+2%>>
							<%= @user.sortedAccounts.find { |account| account.id == tx_dr_proposed.keys[idx].to_i }.name %>
						</span>
						<%= f.hidden_field categoryAccountType, value: tx_dr_proposed.keys[idx] %>
						<%= f.hidden_field categoryAccountType + "_proposed", value: nil %>
						<input type="hidden" name="page" value="<%=params[:page]%>">
					<%end%>
				<%end%>
			<% end %>
		</td>

		<td class="text-center tx align-middle">
			<div class="d-flex justify-content-between">
				<div class="dropdown">
					<a class="btn btn-sm" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" tabindex=-1>
						...
					</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
						<a class="dropdown-item" href="<%= edit_transaction_path(:id => transaction.id)%>">Edit</a>
						<a class="dropdown-item" href="<%= transaction_path(:id => transaction.id)%>">View</a>
						<% if transactionType == 'expense'%>
							<a class="dropdown-item" href="<%= split_expenses_path(:id => transaction.id)%>">Split</a>
						<% end %>
						<% if transaction[:attachments] == 0 %>
							<%= link_to( "Add Attachment", transaction_new_attachment_path(:transaction_id => transaction.id), {:remote => true, 'data-toggle' => 'modal', 'data-backdrop'=>'static','data-target' => '#modal-window', class: "dropdown-item"})  %>
						<% end %>
						<%= link_to( "Delete", transaction, method: :delete, data: { confirm: 'Delete Transaction?' }, class: "dropdown-item") %>
					</div>
				</div>
				<div class="dropdown d-flex justify-content-between">
					<div class="float-start">
						<% if transaction[:attachments] > 0 %>
							<a href="#" id="attachmentDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<%= image_tag("attachment.png", height: '16', width: '16') %>
							</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="attachmentDropdownMenuButton">
								<%= link_to( "Show Attachment", url_for(transaction.attachment), class: "dropdown-item" ) %>
								<%= link_to( 'Delete Attachment', transaction_delete_attachment_url(transaction),
									method: :delete,
									class: "dropdown-item",
									data: { confirm: 'Are you sure?' }) %>
							</div>
						<% end %>
					</div>
					<div>
						<% if !transaction.parent_id.nil? %>
							<a href="#" id="connectedDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<%= image_tag("connected.png", height: '16', width: '16') %>
							</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="connectedDropdownMenuButton">
								<%= link_to( "Show Related", transaction_path(:id => transaction.parent_id), class: "dropdown-item" ) %>
							</div>
						<% else %>
							<%= image_tag("empty.png", height: '16', width: '16') %>
						<% end %>

					</div>
				</div>
			</div>
		</td>
	</tr>
<% end %>
</table>

<div id="modal-window" class="modal hide" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/transactions/edit.html.erb
<h3>Edit transaction</h3>

<%= render 'form' %>

<%= link_to 'Show', transaction_path(@transaction) %>