config/routes.rb
Kgcash::Application.routes.draw do

root :to => 'welcome#index', :constraints => UserRequiredConstraint.new
root :to => 'static_pages#home', :constraints => NoUserRequiredConstraint.new, as: nil

resources :user_sessions

resources :users

resources :transactions, constraints: { id: /\d+/ } do
  get 'new_attachment'
  patch 'update_attachment'
  delete 'delete_attachment'
  collection do
    get 'uncategorized'
    post 'autocategorize'
  end
end

get 'transactions/search', to: 'transactions#search'

resources :documents

resources :transaction_imports

resources :expenses do
  collection do
    post 'split_commit'
  end
  collection do
    get 'split'
  end
end

resources :incomes

resources :payments

resources :asset_transfers

resources :reports do
  collection do
    get 'income', to: 'reports#income'
    get 'cashflow', to: 'reports#cashflow'
    get 'alltime', to: 'reports#alltime'
    get 'alltime_expenses', to: 'reports#alltime_expenses'
    get 'alltime_revenue', to: 'reports#alltime_revenue'
  end
end

resources :accounts do
  collection do
    get 'spending'
  end
end

resources :categories

resources :notes

match 'login' => 'user_sessions#new', :as => :login, via: [:get, :post]
match 'logout' => 'user_sessions#destroy', :as => :logout, via: [:get, :post]

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
	include TransactionControllerConcern

	def index
		@user = current_user

		@year = params.has_key?(:year) ? params[:year].to_i : Date.today.year
		@month = params.has_key?(:month) ? params[:month].to_i : nil
		@category = params.has_key?(:category) ? params[:category].to_i : nil

		items = (params[:items] || Pagy::DEFAULT[:limit]).to_i

		sJoinsAccounts = "LEFT JOIN accounts as accts_cr ON accts_cr.id = transactions.acct_id_cr"

		@pagy, @transactions = pagy(
			@user.transactions
				.joins(sJoinsAccounts)
				.select("transactions.id, tx_date, credit, credit as 'amount', debit, tx_type, details, notes, acct_id_cr, acct_id_dr, parent_id, "\
				"IF(accts_cr.account_type = 'Expense', 'credit', 'debit') as txType, "\
				"(SELECT COUNT(*) from active_storage_attachments A WHERE A.record_id = transactions.id AND A.record_type = 'Transaction' and A.name = 'attachment' ) as attachments"
				)
				.where("(acct_id_dr in (select id from accounts where account_type = 'Asset' or account_type = 'Liability') "\
					"AND acct_id_cr in (select id from accounts where account_type = 'Expense')) "\
						"OR "\
					"(acct_id_cr in (select id from accounts where account_type = 'Asset' or account_type = 'Liability') "\
					"AND acct_id_dr in (select id from accounts where account_type = 'Expense'))")
				.in_account(@category)
				.in_month_year(@month, @year)
				.order(sort_column + ' ' + sort_direction),
				limit: items,
		)

		if !@category.nil?
			cat = @user.accounts.find(@category)
			if !cat.nil?
				@category_name = cat.name
			end
		end

		# Get the accounts that could have been used to spend in this category
		@accountTotals = Hash.new()
		accounts_importable = @user.accounts.importable

		accounts_importable.each do |acct_importable|
			@accountTotals[acct_importable.id] = [acct_importable.name, 0]
		end

		# Build a total value spent on the category per account
		if !@category.nil?
			total = 0
			@transactions.each do |t|
				if t.acct_id_dr == @category && !t.debit.nil?
					acct = Account.find(t.acct_id_cr)
					if @accountTotals.has_key?(t.acct_id_cr)
						@accountTotals[t.acct_id_cr][1] += t.debit
					else
						@accountTotals[t.acct_id_cr] = [acct.name, t.debit]
					end
					total += t.debit
				elsif !t.credit.nil?
					acct = Account.find(t.acct_id_dr)
					if @accountTotals.has_key?(t.acct_id_dr) && !t.credit.nil?
						@accountTotals[t.acct_id_dr][1] -= t.credit
					else
						@accountTotals[t.acct_id_dr] = [acct.name, t.credit * -1]
					end
					total -= t.credit
				end
			end
			@accountTotals[-1] = ["Total", total]
		end

		respond_to do |format|
			format.html #index.html.erb
			format.csv {}
		end
	end

	def split
		@id = params.has_key?(:id) ? params[:id].to_i : 0

		@user = current_user

		@transaction = @user.transactions.find(@id)
		@accounts = @user.account_selector

		@transaction_new = @user.transactions.new()
		@transaction_new.tx_date = @transaction.tx_date
		@transaction_new.posting_date = @transaction.posting_date
		@transaction_new.tx_type = @transaction.tx_type
		@transaction_new.details = @transaction.details
		@transaction_new.notes = @transaction.notes
		@transaction_new.debit = 0
		@transaction_new.credit = 0
		@transaction_new.acct_id_cr = @transaction.acct_id_cr
		@transaction_new.acct_id_dr = @transaction.acct_id_dr

		@transaction_list = [@transaction, @transaction_new]

		respond_to do |format|
			format.html
		end
	end

	def split_commit

		user = current_user

		# Get the base transaction
		base_tx_id = params[:tx_id]
		base_transaction = user.transactions.find(base_tx_id)

		# Get the transactions to commit
		transactions = params[:transactions]

		transactions.each do |transaction|
			tx_id = transaction[0]
			tx_params = transaction[1]
			amount_new = tx_params[:credit].gsub(/[^\d\.-]/,'').to_f

			if user.transactions.exists? tx_id

				# Find the existing transaction
				tx_existing = user.transactions.find(tx_id)

				# Modify values for the split transaction
				tx_existing.debit = amount_new
				tx_existing.credit = amount_new
				tx_existing.acct_id_dr = tx_params[:acct_id_dr]
				tx_existing.notes = tx_params[:notes]
				tx_existing.parent_id = base_transaction.id

				# Copy attachment if there is one
				if base_transaction.attachment.attached?
					tx_existing.attachment.attach \
					:io           => StringIO.new(base_transaction.attachment.download),
					:filename     => base_transaction.attachment.filename,
					:content_type => base_transaction.attachment.content_type
				end

				# Update the transaction hash
				tx_existing.tx_hash = tx_existing.build_hash

				#Save
				tx_existing.save
			else
				# Copy attribute values from the base transaction
				tx_new = Transaction.new(base_transaction.attributes.slice(*Transaction.attribute_names))

				# Modify values for the split transaction
				tx_new.id = nil
				tx_new.debit = amount_new
				tx_new.credit = amount_new
				tx_new.acct_id_dr = tx_params[:acct_id_dr]
				tx_new.notes = tx_params[:notes]
				tx_new.parent_id = base_transaction.id
				tx_new.created_at = Time.now

				# Copy attachment if there is one
				if base_transaction.attachment.attached?
					tx_new.attachment.attach \
					:io           => StringIO.new(base_transaction.attachment.download),
					:filename     => base_transaction.attachment.filename,
					:content_type => base_transaction.attachment.content_type
				end

				# Update the transaction hash
				tx_new.tx_hash = tx_new.build_hash

				# Save
				tx_new.save
			end
		end

		respond_to do |format|
			format.html { redirect_to(transaction_path(:id => base_tx_id)) }
		end
	end

	def update
	end



end

app/views/expenses/_category_heading.html.erb
<% if !@category_name.nil? %>
	<h3>Expenses<%= " - " + @category_name%></h3>
<% elsif %>
	<h3>Expenses</h3>
<% end %>

app/views/expenses/_expense_list.html.erb
<table class="table table-striped table-condensed">
	<tr>
		<th width="120px"><%= sortable "tx_date", "Date" %></th>
		<th><%= sortable "account_id", "Account" %></th>
		<th><%= sortable "details" %></th>
		<th><%= sortable "notes" %></th>
		<th width="75px"><%= sortable "credit", "Amount" %></th>
		<th>Category</th>
		<th>Action</th>
	</tr>

<% transactionType = (local_assigns[:txType]) ? txType : 'expense' %>
<% categoryAccountType = transactionType == 'expense' ? 'acct_id_dr' : 'acct_id_cr' %>
<% txAccountType = transactionType == 'expense' ? 'acct_id_cr' : 'acct_id_dr' %>
<% txAmountClass = transactionType == 'expense' ? 'debit' : 'credit' %>

<% @transactions.each_with_index do |transaction, idx| %>

	<tr>
		<td class="align-middle tx"><%= best_in_place transaction, :tx_date, :as => :date, :display_as => :format_date %></td>
		<td class="align-middle tx"><%= form_for transaction, :remote => true do |f| %>
				<%= f.select txAccountType, options_from_collection_for_select(@user.sortedAccounts,'id','name', transaction[txAccountType]), {}, :class => 'transaction_update select', tabindex: "-1" %>
			<% end %>
		</td>
		<td class="align-middle tx"><%= best_in_place transaction, :details, :as => :textarea %></td>
		<td class="align-middle tx"><%= best_in_place transaction, :notes, :class => 'expense_note', tabindex: (idx+1)*2 %></td>
		<td class="align-middle tx <%= txAmountClass %>"><%= number_to_currency(transaction.amount) %></td>
		<td class="align-middle tx"><%= form_for transaction, :remote => true do |f| %>
				<%= f.hidden_field :debit, value: [transaction.debit.to_i, transaction.credit.to_i].max() %>
				<%= f.select categoryAccountType, options_from_collection_for_select(@user.sortedAccounts,'id','name', transaction[categoryAccountType]), { :include_blank => "select type"}, :class => 'transaction_update select', tabindex: ((idx+1)*2)+1 %>
			<% end %>
		</td>
		<td class="align-middle tx">
			<div class="dropdown">

				<a class="btn btn-sm" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					...
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
					<a class="dropdown-item" href="<%= edit_transaction_path(:id => transaction.id)%>">Edit</a>
					<a class="dropdown-item" href="<%= transaction_path(:id => transaction.id)%>">View</a>
					<a class="dropdown-item" href="<%= split_expenses_path(:id => transaction.id)%>">Split</a>
					<%= link_to( "Delete", transaction, method: :delete, data: { confirm: 'Delete Transaction?' }, class: "dropdown-item") %>
				</div>
			</div>
		</td>
	</tr>
<% end %>
</table>

app/views/expenses/_header.html.erb
	<div class="row">
		<div class="col-md-2">
			<strong>Transaction Date:</strong>
		</div>
		<div class="col-md-2">
			<%= @transaction.tx_date%>
		</div>

		<div class="col-md-1">
			<strong>Account:</strong>
		</div>
		<div class="col-md-2">
			<%= @transaction.acct_id_cr%>
		</div>

		<div class="col-md-1">
			<strong>Amount:</strong>
		</div>
		<div class="col-md-2">
			<%= number_to_currency(@transaction.credit) %>
		</div>
	</div>

app/views/expenses/_split_row.html.erb
<% transactions if local_assigns[:transactions] %>
<% f if local_assigns[:form]%>

<% transactions.each do |tx| %>
	<%= f.fields_for 'transactions', index: (tx.id.nil? ? 0 : tx.id) do |tx_form| %>
		<tr>
			<td><%= tx_form.hidden_field :details, value: tx.details %>
				<%= tx.details %>
			</td>
			<td><%= tx_form.text_field :notes, value: tx.notes, id: (tx.id.nil? ? 0 : tx.id)%>
			<td><%= tx_form.text_field :credit, value: number_to_currency(tx.credit), class: "split_item_amount" %></td>
			<td>
				<%= tx_form.hidden_field :debit, value: tx.debit.nil? || tx.debit == 0 ? tx.credit : tx.debit  %>
				<%= tx_form.select :acct_id_dr, options_from_collection_for_select(@user.sortedAccounts,'id','name', tx.acct_id_dr), { :include_blank => "select type"} %>
			</td>
		</tr>
	<% end %>
<% end %>

app/views/expenses/index.html.erb
<%= render partial: "category_heading" %>

<div class="row lead">
	<div class="col-md-3">
		<%= render 'transactions/year_navigator' %>
	</div>
</div>

<div class="row lead">
	<div class="col-md-3">
		<%= render 'transactions/month_navigator' %>
	</div>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-10">
        <%== pagy_bootstrap_nav(@pagy) %>
    </div>
    <div class="col-md-2">
      <%= link_to "View Uncategorized", uncategorized_transactions_path(:tx_type => 'debit') %>
    </div>
  </div>
</div>

<%= render partial: "transactions/typed_transaction_list", locals: {txType: 'expense'} %>

<div class="row">
	<div class="col-md-12 text-right">
		<button id="exportCsv" type="submit" class="btn mb-1" onclick="exportCsv()">Download as CSV</button>
	</div>
</div>

<% if !@accountTotals.nil? %>
	<h3>Amount per Account</h3>

	<div class="row">
		<div class="col-md-3">
			<table class="table table-striped table-condensed">
				<tr>
					<th width="120px">Account</th>
					<th class="text-center" width="75px">Amount</th>
				</tr>
				<% @accountTotals.each_with_index do |acctTot, idx| %>
				<tr>
					<td><%= acctTot[1][0] %></td>
					<td><%= number_to_currency(acctTot[1][1]) %></td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>
<% end %>

app/views/expenses/split.html.erb
<h3>Split Transaction</h3>
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<div class="card">
				<div class="card-body">
					<%= render 'header' %>
				</div>
			</div>
		</div>
	</div>

	<%= form_with url: split_commit_expenses_path do |f| %>
	<div class="row">
		<div class="col-sm-12">
			<%= f.hidden_field :tx_id, value: @id %>
			<table class="table table-striped table-condensed">
				<tr>
					<th>Details</th>
					<th>Notes</th>
					<th width="75px">Amount</th>
					<th>Category</th>
				</tr>
				<%= render partial: "split_row", locals: {transactions: @transaction_list, f: f} %>
				<tr>
					<td></td>
					<td>Totals:</td>
					<td><span id="totalSplitAmount"></span></td>
					<td></td>
				</tr>
			</table>
		</div>
	</div>
	<div class="row justify-content-end">
		<div class="col-md-1">
			<%= f.submit %>
		</div>
	</div>
	<% end %>
</div>