config/routes.rb
Kgcash::Application.routes.draw do

root :to => 'welcome#index', :constraints => UserRequiredConstraint.new
root :to => 'static_pages#home', :constraints => NoUserRequiredConstraint.new, as: nil

resources :user_sessions

resources :users

resources :transactions, constraints: { id: /\d+/ } do
  get 'new_attachment'
  patch 'update_attachment'
  delete 'delete_attachment'
  collection do
    get 'uncategorized'
    post 'autocategorize'
  end
end

get 'transactions/search', to: 'transactions#search'

resources :documents

resources :transaction_imports

resources :expenses do
  collection do
    post 'split_commit'
  end
  collection do
    get 'split'
  end
end

resources :incomes

resources :payments

resources :asset_transfers

resources :reports do
  collection do
    get 'income', to: 'reports#income'
    get 'cashflow', to: 'reports#cashflow'
    get 'alltime', to: 'reports#alltime'
    get 'alltime_expenses', to: 'reports#alltime_expenses'
    get 'alltime_revenue', to: 'reports#alltime_revenue'
  end
end

resources :accounts do
  collection do
    get 'spending'
  end
end

resources :categories

resources :notes

match 'login' => 'user_sessions#new', :as => :login, via: [:get, :post]
match 'logout' => 'user_sessions#destroy', :as => :logout, via: [:get, :post]

end

app/models/account.rb
class Account < ActiveRecord::Base
	include Comparable

	before_save :filter_import_type

	belongs_to :user

	has_many :credit_transactions, class_name: 'Transaction', foreign_key: 'acct_id_cr'
	has_many :debit_transactions, class_name: 'Transaction', foreign_key: 'acct_id_dr'

	SupportedFormats = ["Vancity","RBC Visa","Vancity Visa","Vancity Visa (New)","RBC Chequing"]
	AccountTypes = ["Expense","Income","Asset","Liability"]

	scope :importable, lambda {where("import_class IS NOT NULL")}
	scope :expense, lambda {where("account_type = 'Expense'")}
	scope :income, lambda {where("account_type = 'Income'")}
	scope :asset, lambda {where("account_type = 'Asset'")}
	scope :liability, lambda {where("account_type = 'Liability'")}

	def active_months
		last_tx_date = transactions[0].tx_date
		first_tx_date = transactions[transactions.count-1].tx_date
		months = (last_tx_date.year * 12 + last_tx_date.month) - (first_tx_date.year * 12 + first_tx_date.month)
	end

	def credits(year=nil)
		if year.nil?
			year = Time.now.year
		end
		credit_transactions.where("year(tx_date) = ?", year).sum(:credit)
	end

	def debits(year=nil)
		if year.nil?
			year = Time.now.year
		end
		debit_transactions.where("year(tx_date) = ?", year).sum(:debit)
	end

	def debits_monthly(year=nil)
		if year.nil?
			year = Time.now.year
		end
		debit_transactions.where("year(tx_date) = ?", year).group('month(tx_date)').sum(:debit)
	end

	def credits_monthly(year=nil)
		if year.nil?
			year = Time.now.year
		end
		credit_transactions.where("year(tx_date) = ?", year).group('month(tx_date)').sum(:credit)
	end

	def debits_yearly(max_years=10)
		debit_transactions
			.where('year(tx_date) > ? ', Date.today.year - max_years)
			.group('year(tx_date)').sum(:debit)
	end

	def credits_yearly(max_years=10)
		credit_transactions
			.where('year(tx_date) > ? ', Date.today.year - max_years)
			.group('year(tx_date)').sum(:credit)
	end

	def <=> other
		return 0 if !name && !other.name
		return 1 if !name
		return -1 if !other.name
		name.downcase <=> other.name.downcase
	end

	private

	def filter_import_type
		if import_class == ""
			self.import_class = nil
		end
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

	def index

		@user = current_user

		@year = params.has_key?(:year) ? params[:year].to_i : Date.today.year

		@expenseAccounts = @user.accounts.expense.order(:name)
		@incomeAccounts = @user.accounts.income.order(:name)
		@assetAccounts = @user.accounts.asset.order(:name)
		@liabilityAccounts = @user.accounts.liability.order(:name)

		respond_to do |format|
			format.html #index.html.erb
			format.json {render json: @accounts }
		end
	end

	def spending

		@user = current_user

		accounts = @user.accounts.importable

		@accounts_array = Array.new(0)

		accounts.each do |a|
			transactions = Transaction.select("min(tx_date) as tx_first, max(tx_date) as tx_last, count(*) as tx_count")
				.where("acct_id_dr = " + a.id.to_s + " OR acct_id_cr = " + a.id.to_s )

			accountInfo = nil
			unless transactions.nil? or transactions.length < 0
				accountInfo = transactions[0]

				hashAccountInfo = {
					"account" => a,
					"tx_count" => accountInfo.tx_count,
				}

				if accountInfo.tx_count > 0
					hashAccountInfo["tx_first"] = accountInfo.tx_first
					hashAccountInfo["tx_last"] = accountInfo.tx_last
				end

				@accounts_array << hashAccountInfo
			end
		end

		respond_to do |format|
			format.html #index.html.erb
			format.json {render json: @accounts }
		end
	end

	def edit
		@user = current_user
		@account = @user.accounts.find(params[:id])
	end

	def create
		@user = current_user
		@account = @user.accounts.create(account_params)

		respond_to do |format|
			if @account.save
				format.html { redirect_to(accounts_path, :notice => 'Account was successfully created for user.') }
				format.json { render json: @account, status: :created, location: @account }
			else
				format.html { render action: "new" }
				format.json { render json: @account.errors, status: :unprocessable_entity }
			end
		end
	end

	def show
		@user = current_user
		@year = params.has_key?(:year) ? params[:year].to_i : Date.today.year

		@account = @user.accounts.find(params[:id])

		debits_monthly = @account.debits_monthly(@year)
		credits_monthly = @account.credits_monthly(@year)

		# chart data structure
		barData = Array.new(0)
		barDataDebits = {name: "Debits", values: Array.new(0)}
		barDataCredits = {name: "Credits", values: Array.new(0)}
		barDataBalance = {name: "Balance", values: Array.new(0)}

		# table data structures
		@monthly_balance = Array.new(0)
		@yearly_balance = Array.new(0)

		(1..12).each do |month|

			monthHash = {month: Date::MONTHNAMES[month][0..2]}

			monthDebit = 0
			if debits_monthly.has_key?(month)
				monthDebit = debits_monthly[month]
			end

			barDataDebits[:values] << monthDebit
			monthHash[:debits] = monthDebit

			monthCredit = 0
			if credits_monthly.has_key?(month)
				monthCredit = credits_monthly[month]
			end

			monthHash[:credits] = monthCredit
			barDataCredits[:values] << monthCredit

			monthHash[:balance] = (monthCredit - monthDebit).abs
			barDataBalance[:values] << (monthCredit - monthDebit).abs

			@monthly_balance << monthHash
		end

		gon.echartMonthly = barData << barDataDebits << barDataCredits << barDataBalance

		debits_yearly = @account.debits_yearly()
		credits_yearly = @account.credits_yearly()

		# Get the full set of years covered by each hash
		years = Array.new(0)
		debits_yearly.keys.each do |year|
			years << year
		end
		credits_yearly.keys.each do |year|
			years << year
		end
		# Process the arrays into a single array by removing duplicates, nils sorting
		# and filling in any gaps
		years = years.compact.uniq.sort
		if years.length > 1 && years.min < years.max
			years = (years.min..years.max).to_a
		end

		balance_this_year = 0
		years.each do |year|
			yearHash = {year: year}

			yearDebit = 0
			if debits_yearly.has_key?(year)
				yearDebit = debits_yearly[year]
			else
				yearDebit = 0
			end

			yearHash[:debits] = yearDebit

			yearCredit = 0
			if credits_yearly.has_key?(year)
				yearCredit = credits_yearly[year]
			else
				yearCredit = 0
			end

			yearHash[:credits] = yearCredit

			yearHash[:balance] = (yearCredit - yearDebit).abs

			if year == Date.today.year
				balance_this_year = yearHash[:balance]
			end

			@yearly_balance << yearHash
		end

		## Calculate the projected balance for this year
		@projected_this_year = DateMath.annualize_ytd_amount( balance_this_year )

		## Calculate the average annual balance
		annualized_yearly_balance = @yearly_balance.reject { |year_hash| year_hash[:year] == Date.today.year }
		annualized_yearly_balance << {year: Date.today.year, balance: @projected_this_year}
		total_balance = annualized_yearly_balance.sum { |year_hash| year_hash[:balance] }
		@average_yearly_balance = total_balance.to_f / annualized_yearly_balance.size

		## Calculate the average annual growth rate
		prev_year_amount = 0
		annualized_yearly_balance.each do |year_hash|
			if prev_year_amount == 0
				year_hash[:change] = 0
			else
				year_hash[:change] = (year_hash[:balance] - prev_year_amount) / prev_year_amount
			end
			prev_year_amount = year_hash[:balance]
		end

		count = 0
		total_change = 0
		annualized_yearly_balance.each do |year_hash|
			if year_hash[:change] != 0
				total_change += year_hash[:change]
				count += 1
			end
		end

		@aagr = total_change.to_f / count

		## Calculate the CAGR
		start_value = annualized_yearly_balance[0][:balance]
		end_value = annualized_yearly_balance[annualized_yearly_balance.size - 1][:balance]
		@cagr = 0
		if start_value != 0 && annualized_yearly_balance.size > 0
			@cagr = ((end_value / start_value) ** (1/annualized_yearly_balance.size.to_f)) - 1
		end

		## Calculate the monthly average
		@monthly_average = @projected_this_year / 12


		respond_to do |format|
			format.html #show.html.erb
			format.json {render json: @account}
		end
	end

	def update
		@account = Account.find(params[:id])

		respond_to do |format|
			if @account.update(account_params)
				format.html { redirect_to accounts_path, notice: 'Account was successfully updated.' }
				format.json { respond_with_bip(@account) }
				format.js {render :nothing => true }
			else
				format.html { render action: "edit" }
				format.json { render json: @account.errors, status: :unprocessable_entity }
			end
		end
	end

	def new
		@user = current_user
		@account = Account.new

		respond_to do |format|
			format.html # new.html.erb
			format.json {render json: @account}
		end
	end

	def destroy
		@user = current_user
		@account = @user.accounts.find(params[:id])
		@account.destroy

		respond_to do |format|
			format.html { redirect_to :action => 'index' }
			format.js   { render :nothing => true }
			format.json { head :ok }
		end
	end

	private

	def account_params
		params.require(:account).permit(:name, :description, :account_type, :import_class, :year)
	end

end

app/views/accounts/_accountGroup.html.erb
<% if !accounts.nil? %>

<div class="accordion" id="<%= id + 'Accordion'%>">
  <div class="card">
	<div class="card-header" id="<%= id + 'Heading'%>">
	  <h2 class="mb-0">
		<button class="btn" type="button" data-toggle="collapse" data-target="#<%= id + 'Collapse'%>" aria-expanded="false" aria-controls="<%= id + 'Collapse'%>">
		  <h3><%= title %></h3>
		</button>
	  </h2>
	</div>

	<div id="<%= id + 'Collapse'%>" class="collapse" aria-labelledby="<%= id + 'Heading'%>" data-parent="#<%= id + 'Accordion'%>">
	  <div class="card-body">
		<table class="table table-striped table-condensed">
		  <tr>
			<th>Name</th>
			<th>Description</th>
			<th>Credit</th>
			<th>Debit</th>
			<th>Balance</th>
			<th>Action</th>
		  </tr>

		  <% accounts.each do |acct| %>
		  <% credits = acct.credits(year)%>
		  <% debits = acct.debits(year)%>
		  <% balance = (credits - debits).abs%>
			<tr>
			  <td><%= link_to acct.name, account_path(acct)%></td>
			  <td><%= acct.description %></td>
			  <td><%= number_to_currency( credits, precision:0) %></td>
			  <td><%= number_to_currency( debits, precision: 0) %></td>
			  <td><%= number_to_currency( balance, precision:0) %></td>
			  <td>
				<div class="dropdown">
				  <a class="btn btn-sm" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					...
				  </a>
				  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
					<a class="dropdown-item" href="<%= edit_account_path(:id => acct.id)%>">Edit</a>
					<%= link_to( "Delete", acct, method: :delete, data: { confirm: 'Delete Category?' }, class: "dropdown-item") %>
				  </div>
				</div>
			  </td>
			</tr>
		  <% end %>
		</table>
	  </div>
	</div>
  </div>
</div>

<% end %>

app/views/accounts/_form.html.erb
<%= form_with(model: @account, local: true) do |form| %>
  <div class="row px-4">
    <div class="col-md-3">
      <h3>Edit Account:</h3>

      <table class="table">
        <tbody>
          <tr>
            <td class="bg-light"><strong>Name</strong></td>
            <td><%= form.text_field :name, class: 'form-control' %></td>
          </tr>
          <tr>
            <td class="bg-light"><strong>Description</strong></td>
            <td><%= form.text_area :description, class: 'form-control' %></td>
          </tr>
          <tr>
            <td class="bg-light"><strong>Account Type</strong></td>
            <td><%= form.select :account_type, Account::AccountTypes, {}, class: 'form-control' %></td>
          </tr>
          <tr>
            <td class="bg-light"><strong>Import Class</strong></td>
            <td><%= form.select :import_class, Account::SupportedFormats, {:include_blank => ''}, class: 'form-control' %></td>
          </tr>
        </tbody>
      </table>

      <table class="table table-borderless">
        <thead>
          <tr>
            <td>
              <%= link_to 'Save', '#', class: 'btn btn-primary', id: 'submit-form' %>
              <% if !@account.id.nil? %>
                <%= link_to 'Delete', account_path(@account), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              <% end %>
              <%= link_to "Back to accounts", accounts_path, class: 'btn btn-secondary' %>
            </td>
          </tr>
        </thead>
      </table>
    </div>
  </div>
<% end %>

<script>
  document.getElementById('submit-form').addEventListener('click', function(e) {
    e.preventDefault();
    document.querySelector('form').submit();
  });
</script>

app/views/accounts/edit.html.erb
<%= render 'form' %>

app/views/accounts/index.html.erb
<div class="col-md-6 mx-auto">

	<h3>My Accounts</h3>

	<%= render partial: 'transactions/year_navigator', locals: { year: @year } %>

	<%= render partial: 'accountGroup', locals: { title: 'Expense Accounts', id: 'expenses', accounts: @expenseAccounts, year: @year }  %>
	<%= render partial: 'accountGroup', locals: { title: 'Income Accounts', id: 'income', accounts: @incomeAccounts, year: @year }  %>
	<%= render partial: 'accountGroup', locals: { title: 'Asset Accounts', id: 'asset', accounts: @assetAccounts, year: @year }  %>
	<%= render partial: 'accountGroup', locals: { title: 'Liability Accounts', id: 'liability', accounts: @liabilityAccounts, year: @year }  %>

	<%= link_to 'New Account', new_account_path %>
</div>

<br />

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<script>
	var multiBarOptions = getEchartsMultibarOptions(gon.echartMonthly);
	multiBarOptions.xAxis.data = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
	multiBarOptions.xAxis.name = <%= @year %>;
</script>

<script>
	$(document).ready(function() {

		// Set the active tab in local storage and show the tab when a tab is clicked
		$('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
			localStorage.setItem('activeTab', $(e.target).attr('href'));
			$('.tab-pane').hide();
			var tab = $($(e.target).attr('href'));
			tab.show();

			// Redraw the chart if the shown tab is the chart tab
			if ($(e.target).attr('href') === '#chartMonthly') {
				myChart.resize();
			}
		});

		// Check if there's a saved tab
		var activeTab = localStorage.getItem('activeTab');
		if (activeTab) {
			$('#myTab a[href="' + activeTab + '"]').tab('show');
			$(activeTab).show();

		} else {
			// Show the default tab if no tab is saved
			$('#myTab a[href="#chartMonthly"]').tab('show');
			$('#chartMonthly').show();
		}

	});
</script>


<div class="row">
	<div class="col-md-3">
		<h3>Account Details</h3>
	</div>
	<div class="col-md-7">
		<h3>Monthly Balance</h3>
	</div>
	<div class="col-md-2">
		<h3><%= render partial: 'transactions/year_navigator', locals: { year: @year } %></h3>
	</div>
</div>

<div class="row">
	<div class="col-md-3">
		<table class="table">
			<tbody>
				<tr>
					<td class="bg-light" style="width: 30%;"><strong>Name</strong></td>
					<td><%= @account.name %></td>
				</tr>
				<tr>
					<td class="bg-light" style="width: 30%;"><strong>Description</strong></td>
					<td><%= @account.description %></td>
				</tr>
				<tr>
					<td class="bg-light" style="width: 30%;"><strong>Account Type</strong></td>
					<td><%= @account.account_type %></td>
				</tr>
				<tr>
					<td class="bg-light" style="width: 30%;"><strong>Import Class</strong></td>
					<td><%= @account.import_class %></td>
				</tr>
			</tbody>
		</table>

		<%= link_to 'Edit', edit_account_path(@account), class: 'btn btn-primary' %>
		<%= link_to 'Back to Accounts', accounts_path, class: 'btn btn-secondary' %>
	</div>
	<div class="col-md-8">
		<ul class="nav nav-tabs" id="myTab" role="tablist">
			<li class="nav-item">
				<a class="nav-link" id="table-tab" data-toggle="tab" href="#table" role="tab" aria-controls="table" aria-selected="false">Table</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" id="chartMonthly-tab" data-toggle="tab" href="#chartMonthly" role="tab" aria-controls="chartMonthly" aria-selected="true">Chart</a>
			</li>
		</ul>
		<div class="tab-content" id="myTabContent">
			<div class="tab-pane fade" id="chartMonthly" role="tabpanel" aria-labelledby="chart-tab">
				<%= render partial: "reports/multiBarChart", locals: {
					domId: "monthlyBalanceChart",
					data: "multiBarOptions",
					height: "400"
					}
				%>
			</div>
			<div class="tab-pane fade" id="table" role="tabpanel" aria-labelledby="table-tab">
				<div class="table-responsive" style="height:400px; overflow:auto;">
					<table class="table table-striped table-condensed text-center">
						<tr>
							<th>Month</th>
							<% @monthly_balance.each do |month| %>
								<th><%= month[:month] %></th>
							<% end %>
						</tr>
						<tr>
							<th>Credits</th>
							<% @monthly_balance.each do |month| %>
								<td><%= number_to_currency(month[:credits], precision: 0) %></td>
							<% end %>
						</tr>
						<tr>
							<th>Debits</th>
							<% @monthly_balance.each do |month| %>
								<td><%= number_to_currency(month[:debits], precision: 0) %></td>
							<% end %>
						</tr>
						<tr>
							<th>Balance</th>
							<% @monthly_balance.each_with_index do |month, i| %>
								<td>
									<% if @account.account_type == "Expense" %>
										<%= link_to number_to_currency(month[:balance], precision: 0), expenses_path({category: @account.id.to_s, year: @year, month: i+1}) %>
									<% elsif @account.account_type == "Income" %>
										<%= link_to number_to_currency(month[:balance], precision: 0), incomes_path({category: @account.id.to_s, year: @year, month: i+1}) %>
									<% else %>
										<%= number_to_currency(month[:balance], precision: 0) %>
									<% end %>
								</td>
							<% end %>
						</tr>
					</table>

				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-3">
		<h3>Account Stats</h3>
	</div>
	<div class="col-md-8">
		<h3>Annual Balance</h3>
	</div>
</div>

<div class="row">
	<div class="col-md-3">
		<table class="table">
			<tbody>
				<tr>
					<td class="bg-light" style="width: 30%;"><strong>10 Year Average</strong></td>
					<td><%= number_to_currency(@average_yearly_balance, precision: 0) %></td>
				</tr>
				<tr>
					<td class="bg-light" style="width: 30%;"><strong>10 Year CAGR</strong></td>
					<td><%= number_to_percentage(@cagr * 100, precision: 2) %></td>
				</tr>
				<tr>
					<td class="bg-light" style="width: 30%;"><strong>10 Year AAGR</strong></td>
					<td><%= number_to_percentage(@aagr * 100, precision: 2) %></td>
				</tr>
				<tr>
					<td class="bg-light" style="width: 30%;"><strong><%= Date.today.year %> Monthly</strong></td>
					<td><%= number_to_currency(@monthly_average, precision: 0) %></td>
				</tr>
				<tr>
					<td class="bg-light" style="width: 30%;"><strong><%= Date.today.year %> Projected Total</strong></td>
					<td><%= number_to_currency(@projected_this_year, precision: 0) %></td>
				</tr>
			</tbody>
		</table>
	</div>

	<div class="col-md-8">
		<table class="table table-striped table-condensed text-center">
			<tr>
				<th>Year</th>
				<% @yearly_balance.each do |year| %>
					<th><%= year[:year] %></th>
				<% end %>
			</tr>
			<tr>
				<th>Credits</th>
				<% @yearly_balance.each do |year| %>
					<td><%= number_to_currency(year[:credits], precision: 0) %></td>
				<% end %>
			</tr>
			<tr>
				<th>Debits</th>
				<% @yearly_balance.each do |year| %>
					<td><%= number_to_currency(year[:debits], precision: 0) %></td>
				<% end %>
			</tr>
			<tr>
				<th>Balance</th>
				<% @yearly_balance.each do |year| %>
					<th><%= number_to_currency(year[:balance], precision: 0) %></th>
				<% end %>
			</tr>
		</table>
	</div>
</div>

app/views/accounts/spending.html.erb
<div class="col-md-6 mx-auto">

	<h3>My Spending Accounts</h3>

	<table class="table table-striped table-condensed">
		<tr>
			<th>Name</th>
			<th>Account Type</th>
			<th>First Transaction</th>
			<th>Most Recent</th>
			<th>Transactions</th>
			<th></th>
		</tr>

		<% @accounts_array.each do |account_info| %>
			<% account = account_info["account"] %>
			<tr>
				<td><%= account.name %></td>
				<td><%= account.account_type %></td>

				<% if account_info["tx_count"] > 0 %>
					<td><%= account_info["tx_first"].strftime('%b %e, %Y') %></td>
					<td><%= account_info["tx_last"].strftime('%b %e, %Y') %></td>
				<% else %>
					<td>-</td><td>-</td>
				<% end %>

				<td><%= account_info["tx_count"] %></td>

				<td>
					<%= link_to 'Show', account_path(account), class: 'btn btn-primary' %>
					<%= link_to 'Edit', edit_account_path(account), class: 'btn btn-warning' %>
					<%= link_to 'Delete', account_path(account), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
				</td>
			</tr>
		<% end %>

	</table>
</div>